version: 0.0
os: linux
files:
  - source: /aws-basic-app/backend     # The source is the backend directory in the repo
    destination: /home/ec2-user/myapp  # Deploy to this path on the EC2 instance

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/start_pm2.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/pm2_restart.sh
      timeout: 300
      runas: ec2-user